import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * Data model notes:
 *
 * - `drains` are seeded once with real, named Lagos flood-prone locations
 *   (see convex/seed.ts). We deliberately did NOT invent fictional drain IDs.
 *
 * - `readings` represent sensor data (water level / blockage) for a drain
 *   at a point in time. `source` distinguishes how the reading was produced:
 *     - "simulated": generated by convex/simulate.ts on a cron because no
 *       physical IoT sensors are deployed yet. This is a demo/prototype,
 *       not live hardware.
 *     - "community_report": a human-submitted report (zero-cost real data
 *       source), same shape a real ultrasonic sensor payload would use.
 *   Keeping one shape for both means a real device can start posting
 *   readings (e.g. a new "device" source) without any schema change later.
 *
 * - `rainfallSnapshots` stores real weather data fetched from Open-Meteo
 *   (see convex/rainfall.ts): 24h rainfall total, current temperature, and
 *   a current-conditions code/label. Stored (not fetched inline) so queries
 *   can read the latest value without making a network call, and so the
 *   dashboard can show a trend.
 */
export default defineSchema({
  drains: defineTable({
    name: v.string(),
    zone: v.string(),
    lat: v.number(),
    lng: v.number(),
    description: v.optional(v.string()),
  }),

  readings: defineTable({
    drainId: v.id("drains"),
    waterLevelCm: v.number(),
    blockagePct: v.number(),
    source: v.union(v.literal("simulated"), v.literal("community_report")),
  }).index("by_drain", ["drainId"]),

  rainfallSnapshots: defineTable({
    rainfall24hMm: v.number(),
    // Optional: rows written before the weather fields were added won't
    // have these. Old data stays valid; the dashboard treats missing
    // values as "not available yet" until the next cron refresh.
    temperatureC: v.optional(v.number()),
    weatherCode: v.optional(v.number()),
    condition: v.optional(v.string()),
    // Volumetric soil moisture (m3/m3), 0-1cm depth -- real Open-Meteo
    // data, used as the "Soil Saturation" risk driver.
    soilMoisture: v.optional(v.number()),
    fetchedAt: v.number(),
  }),
});
